"""baseline schema

Revision ID: 120d2ef665ee
Revises: 
Create Date: 2026-08-01 16:34:07.510624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '120d2ef665ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('oauth_identities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_oauth_provider_user')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='created', nullable=False),
    sa.Column('setup_genre', sa.Text(), nullable=False),
    sa.Column('setup_art_style', sa.Text(), nullable=False),
    sa.Column('setup_setting', sa.Text(), nullable=False),
    sa.Column('setup_protagonist_name', sa.Text(), nullable=False),
    sa.Column('setup_protagonist_personality', sa.Text(), nullable=False),
    sa.Column('setup_tone', sa.Text(), nullable=False),
    sa.Column('setup_premise', sa.Text(), nullable=True),
    sa.Column('world_lore', sa.Text(), nullable=True),
    sa.Column('plot_arc', sa.Text(), nullable=True),
    sa.Column('current_scene_id', sa.String(), nullable=True),
    sa.Column('current_label', sa.String(), server_default='Start', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_played_at', sa.DateTime(), nullable=True),
    sa.Column('story_spine', sa.Text(), nullable=True),
    sa.Column('endings', sa.Text(), nullable=True),
    sa.Column('alignment_state', sa.Text(), server_default='{}', nullable=True),
    sa.Column('current_beat_index', sa.Integer(), server_default='0', nullable=True),
    sa.Column('chosen_ending_id', sa.String(), nullable=True),
    sa.Column('parent_session_id', sa.String(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), server_default='1', nullable=True),
    sa.Column('storygen_engine', sa.String(), server_default='monolith', nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), server_default='private', nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('like_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('comment_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('play_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_sum', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_sessions_visibility_published', 'sessions', ['visibility', 'published_at'], unique=False)
    op.create_index(op.f('ix_sessions_owner_id'), 'sessions', ['owner_id'], unique=False)
    op.create_table('beat_expansions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('beat_index', sa.Integer(), nullable=False),
    sa.Column('source_choice_tag', sa.String(), server_default='', nullable=False),
    sa.Column('statements', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'beat_index', 'source_choice_tag')
    )
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.String(), server_default='#FFFFFF', nullable=False),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('backstory', sa.Text(), nullable=True),
    sa.Column('relationship', sa.Text(), nullable=True),
    sa.Column('speech_style', sa.Text(), nullable=True),
    sa.Column('quirks', sa.Text(), nullable=True),
    sa.Column('sprites_generated', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_dynamic', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('voice_caption', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'session_id')
    )
    op.create_index(op.f('ix_characters_session_id'), 'characters', ['session_id'], unique=False)
    op.create_table('dialogue_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('label_context', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dialogue_history_session', 'dialogue_history', ['session_id', 'created_at'], unique=False)
    op.create_table('ending_dialogue',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('ending_id', sa.String(), nullable=False),
    sa.Column('statements', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'ending_id')
    )
    op.create_table('playthroughs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('story_id', sa.String(), nullable=False),
    sa.Column('current_label', sa.String(), server_default='Start', nullable=True),
    sa.Column('statement_index', sa.Integer(), server_default='0', nullable=True),
    sa.Column('current_scene_id', sa.String(), nullable=True),
    sa.Column('current_beat_index', sa.Integer(), server_default='0', nullable=True),
    sa.Column('alignment_state', sa.Text(), server_default='{}', nullable=True),
    sa.Column('chosen_ending_id', sa.String(), nullable=True),
    sa.Column('last_played_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'story_id', name='uq_playthrough_user_story')
    )
    op.create_table('saves',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('current_label', sa.String(), nullable=False),
    sa.Column('statement_index', sa.Integer(), server_default='0', nullable=True),
    sa.Column('current_scene_id', sa.String(), nullable=True),
    sa.Column('current_beat_index', sa.Integer(), server_default='0', nullable=True),
    sa.Column('alignment_state', sa.Text(), nullable=True),
    sa.Column('chosen_ending_id', sa.String(), nullable=True),
    sa.Column('visible_characters', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_saves_session', 'saves', ['session_id', 'created_at'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('narrative_context', sa.Text(), nullable=True),
    sa.Column('image_generated', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_dynamic', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'session_id')
    )
    op.create_index(op.f('ix_scenes_session_id'), 'scenes', ['session_id'], unique=False)
    op.create_table('script_labels',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('label_name', sa.String(), nullable=False),
    sa.Column('statements', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'label_name')
    )
    op.create_index(op.f('ix_script_labels_session_id'), 'script_labels', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_labels_session_id'), table_name='script_labels')
    op.drop_table('script_labels')
    op.drop_index(op.f('ix_scenes_session_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index('idx_saves_session', table_name='saves')
    op.drop_table('saves')
    op.drop_table('playthroughs')
    op.drop_table('ending_dialogue')
    op.drop_index('idx_dialogue_history_session', table_name='dialogue_history')
    op.drop_table('dialogue_history')
    op.drop_index(op.f('ix_characters_session_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_table('beat_expansions')
    op.drop_index(op.f('ix_sessions_owner_id'), table_name='sessions')
    op.drop_index('idx_sessions_visibility_published', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('oauth_identities')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('users')
    # ### end Alembic commands ###
