"""billing: payment failure details and refund clawback

Revision ID: 5ec5072154ac
Revises: 6aca22e1e91e
Create Date: 2026-08-20 20:50:48.682349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec5072154ac'
down_revision: Union[str, Sequence[str], None] = '6aca22e1e91e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refunds',
    sa.Column('cf_refund_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('refund_id', sa.String(), nullable=True),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('refund_type', sa.String(), nullable=True),
    sa.Column('status_description', sa.Text(), nullable=True),
    sa.Column('credits_reclaimed', sa.Integer(), nullable=True),
    sa.Column('reclaimed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['payment_orders.order_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cf_refund_id')
    )
    op.create_index(op.f('ix_refunds_order_id'), 'refunds', ['order_id'], unique=False)
    op.add_column('payment_orders', sa.Column('failure_code', sa.String(), nullable=True))
    op.add_column('payment_orders', sa.Column('failure_reason', sa.String(), nullable=True))
    op.add_column('payment_orders', sa.Column('failure_description', sa.Text(), nullable=True))
    op.add_column('payment_orders', sa.Column('last_event_type', sa.String(), nullable=True))
    op.add_column('payment_orders', sa.Column('refunded_paise', sa.Integer(), server_default='0', nullable=False))
    op.add_column('payment_orders', sa.Column('credits_reclaimed', sa.Integer(), server_default='0', nullable=False))
    op.add_column('payment_orders', sa.Column('refunded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_orders', 'refunded_at')
    op.drop_column('payment_orders', 'credits_reclaimed')
    op.drop_column('payment_orders', 'refunded_paise')
    op.drop_column('payment_orders', 'last_event_type')
    op.drop_column('payment_orders', 'failure_description')
    op.drop_column('payment_orders', 'failure_reason')
    op.drop_column('payment_orders', 'failure_code')
    op.drop_index(op.f('ix_refunds_order_id'), table_name='refunds')
    op.drop_table('refunds')
    # ### end Alembic commands ###
