"""billing: credit accounts, ledger, payment orders, webhook events

Revision ID: 6aca22e1e91e
Revises: 58a484645740
Create Date: 2026-08-20 19:46:17.221382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aca22e1e91e'
down_revision: Union[str, Sequence[str], None] = '58a484645740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature')
    )
    op.create_table('credit_accounts',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lifetime_purchased', sa.Integer(), server_default='0', nullable=False),
    sa.Column('free_granted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('credit_ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('ref_type', sa.String(), nullable=True),
    sa.Column('ref_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('idx_credit_ledger_user_created', 'credit_ledger', ['user_id', 'created_at'], unique=False)
    op.create_table('payment_orders',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('pack_id', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('amount_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), server_default='INR', nullable=False),
    sa.Column('status', sa.String(), server_default='created', nullable=False),
    sa.Column('customer_phone', sa.String(), nullable=True),
    sa.Column('cf_order_id', sa.String(), nullable=True),
    sa.Column('payment_session_id', sa.Text(), nullable=True),
    sa.Column('cf_payment_id', sa.String(), nullable=True),
    sa.Column('credited_at', sa.DateTime(), nullable=True),
    sa.Column('raw_status_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_payment_orders_user_id'), 'payment_orders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_orders_user_id'), table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index('idx_credit_ledger_user_created', table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_table('credit_accounts')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
