"""Resume an interrupted generation pipeline for a session.

Walks the session's stored state and fills in whatever the original pipeline
didn't finish: character sprites + overlays, scene backgrounds, the opening
script (if missing — regenerated by asking Gemini to expand beat 0 as the
opening), and the per-line TTS audio.

Usage:
    python -m app.complete_generation <session_id>
"""
from __future__ import annotations

import json
import sys

from google.genai import types

from app.db.database import init_database, db
from app.db.queries import characters as character_queries
from app.db.queries import scenes as scene_queries
from app.db.queries import sessions as session_queries
from app.logger import logger
from app.services import animation_generator, script_builder, session_service, tts_generator
from app.services.ai import image_generator, story_generator
from app.services.ai.gemini_client import get_client, models


def _generate_opening_script(session: dict, beat0: dict, scenes: list, characters: list) -> list[dict]:
    """One-shot Gemini call to produce the opening script for beat 0.

    Mirrors the openingScript schema the world prompt would have emitted —
    statements only (no choices; those come from the spine).
    """
    world_lore = json.loads(session.get("world_lore") or "{}")
    plot_arc = json.loads(session.get("plot_arc") or "{}")
    setup_setting = session["setup_setting"]
    protagonist = session["setup_protagonist_name"]
    tone = session["setup_tone"]

    char_lines = "\n".join(
        f'- {c["id"]} ({c["name"]}): {(c.get("personality") or "")[:200]}. '
        f'Speech: {(c.get("speech_style") or "")[:80]}'
        for c in characters
    )
    scene_lines = "\n".join(
        f'- {s["id"]} ({s["name"]}): {(s.get("description") or "")[:150]}'
        for s in scenes
    )

    prompt = f"""You write the opening script (beat 0) of an interactive visual novel.

WORLD: {world_lore.get("name", "")}
{world_lore.get("description", "")}

SETTING: {setup_setting}
TONE: {tone}
PROTAGONIST (player-controlled, never speak as them): {protagonist}
ARC PREMISE: {plot_arc.get("premise", "")}

OPENING BEAT — {beat0.get("title", "")}
outline: {beat0.get("outline", "")}
scene:  {beat0.get("sceneId", "")}
cast:   {", ".join(beat0.get("castIds") or [])}
goal:   {beat0.get("narrativeGoal", "")}

CHARACTERS (locked — do not invent new ones):
{char_lines}

SCENES (locked — do not invent new ones):
{scene_lines}

YOUR TASK:
Produce ONLY the opening script as a JSON object:
{{
  "openingScript": [
    {{ "type": "scene_change", "sceneId": "<id>" }},
    {{ "type": "show_character", "characterId": "<id>", "position": "left|center|right" }},
    {{ "type": "narration", "text": "..." }},
    {{ "type": "dialogue", "speaker": "<id>", "expression": "happy|sad|angry|surprised|neutral|embarrassed|thinking|scared|determined|smug", "text": "..." }},
    {{ "type": "hide_character", "characterId": "<id>" }}
  ]
}}

RULES:
- 12-20 statements total.
- Start with a scene_change to beat 0's scene, then show 1-2 characters, then narration/dialogue.
- Do NOT include a "choices" array — choices come from the spine.
- Plain ASCII English.
- Use only existing character ids and scene ids."""

    client = get_client()
    response = client.models.generate_content(
        model=models.story_pro,
        contents=[types.Content(role="user", parts=[types.Part.from_text(text=prompt)])],
        config=types.GenerateContentConfig(
            temperature=0.85,
            max_output_tokens=8000,
            response_mime_type="application/json",
        ),
    )
    text = ""
    for part in response.candidates[0].content.parts:
        if getattr(part, "text", None):
            text += part.text
    parsed = story_generator._parse_json_loose(text)
    opening = parsed.get("openingScript") or parsed.get("opening_script") or []
    if not opening:
        raise ValueError("Gemini did not return an openingScript")
    return opening


def _has_label(session_id: str, label: str) -> bool:
    with db() as conn:
        row = conn.execute(
            "SELECT 1 FROM script_labels WHERE session_id = ? AND label_name = ?",
            (session_id, label),
        ).fetchone()
    return row is not None


def complete(session_id: str) -> None:
    session = session_queries.get_by_id(session_id)
    if not session:
        raise RuntimeError(f"Session {session_id} not found")

    art_style = session["setup_art_style"]
    chars = [dict(c) for c in character_queries.get_by_session(session_id)]
    scenes = [dict(s) for s in scene_queries.get_by_session(session_id)]
    spine = json.loads(session.get("story_spine") or "[]")
    endings = json.loads(session.get("endings") or "[]")

    if not spine:
        raise RuntimeError("Spine missing — world generation never finished. Start a fresh session.")

    logger.info("RESUME session %s (%d chars, %d scenes, %d beats, %d endings)",
                session_id, len(chars), len(scenes), len(spine), len(endings))

    # 1. Character sprites — only the ones not flagged as generated.
    for ci, char in enumerate(chars):
        if char.get("sprites_generated"):
            logger.info("[%d/%d] %s: sprites already done", ci + 1, len(chars), char["name"])
            continue
        logger.info("[%d/%d] %s: generating 10 emotion sprites...", ci + 1, len(chars), char["name"])
        char_payload = {"id": char["id"], "name": char["name"], "appearance": char["appearance"]}
        try:
            image_generator.generate_character_sprites(session_id, char_payload, art_style)
            character_queries.mark_sprites_generated(session_id, char["id"])
        except Exception as exc:
            logger.warning("sprite gen failed for %s: %s", char["id"], exc)

    # 2. Overlays — idempotent, skip-if-exists is inside animation_generator.
    for char in chars:
        char_payload = {"id": char["id"], "name": char["name"], "appearance": char["appearance"]}
        try:
            animation_generator.generate_for_character(session_id, char_payload, art_style)
        except Exception as exc:
            logger.warning("overlay gen failed for %s: %s", char["id"], exc)

    # 3. Scene backgrounds — every scene with image_generated=0.
    # Defensively union in ending scenes that may only exist in the endings array.
    scene_ids = {s["id"] for s in scenes}
    for ending in endings:
        fid = ending.get("finalSceneId")
        if fid and fid not in scene_ids:
            logger.info("ending scene %s is missing from scenes — adding stub", fid)
            scene_queries.insert(session_id, {
                "id": fid,
                "name": f"{ending.get('name', 'Ending')} scene",
                "description": ending.get("epilogueOutline") or ending.get("summary") or "",
            })
            scenes.append({"id": fid, "name": f"{ending.get('name','Ending')} scene",
                           "description": ending.get("epilogueOutline") or ending.get("summary") or "",
                           "image_generated": 0})
            scene_ids.add(fid)

    for si, scene in enumerate(scenes):
        if scene.get("image_generated"):
            continue
        logger.info("[%d/%d] background: %s", si + 1, len(scenes), scene["name"])
        try:
            image_generator.generate_background(session_id, {
                "id": scene["id"],
                "name": scene["name"],
                "description": scene.get("description") or scene["name"],
            }, art_style)
            scene_queries.mark_image_generated(session_id, scene["id"])
        except Exception as exc:
            logger.warning("bg gen failed for %s: %s", scene["id"], exc)

    # 4. Opening script — regenerate if the Start label is missing.
    if not _has_label(session_id, "Start"):
        logger.info("Start label missing — calling Gemini to write beat 0 opening...")
        beat0 = spine[0]
        opening = _generate_opening_script(session, beat0, scenes, chars)
        logger.info("got %d statements", len(opening))
        # Build the Start label using the same conversion pipeline as the
        # initial generation path. No choices — the spine appends them when
        # the beat finishes.
        story_data = {"openingScript": opening}
        script = script_builder.build_initial_script(story_data)
        for label_name, statements in script.items():
            script_builder.save_label(session_id, label_name, statements)
        session_queries.update_current_label(session_id, "Start")
    else:
        logger.info("Start label already exists — skipping opening script regen")

    # 5. Voice profiles (no upfront TTS — audio streams on demand at runtime).
    if tts_generator.is_enabled():
        try:
            n_voices = tts_generator.ensure_all_character_voices(session_id)
            logger.info("assigned voice profiles for %d characters", n_voices)
        except Exception as err:
            logger.warning("voice profile pass failed: %s", err)

    # 5b. Pre-render every beat into the cache so runtime is instant.
    from app.services.ai import dialogue_engine
    try:
        n_pregen = dialogue_engine.pre_expand_remaining_beats(session_id)
        logger.info("pre-rendered %d beats", n_pregen)
    except Exception as err:
        logger.warning("beat pre-render pass failed: %s", err)

    # 5c. Pre-render all candidate endings so the final-beat path is a DB
    # lookup with zero live LLM.
    try:
        n_endings = dialogue_engine.pre_expand_all_endings(session_id)
        logger.info("pre-rendered %d endings", n_endings)
    except Exception as err:
        logger.warning("ending pre-render pass failed: %s", err)

    # 5d. Pre-render all audio (opening + beats + endings).
    if tts_generator.is_enabled():
        try:
            def _cb(i, total, preview):
                if i == 1 or i == total or i % 5 == 0:
                    logger.info("[tts %d/%d] %s", i, total, preview)
            n_audio = tts_generator.generate_for_all_session_lines(session_id, progress_cb=_cb)
            logger.info("TTS pre-rendered %d audio files", n_audio)
        except Exception as err:
            logger.warning("TTS pre-render pass failed: %s", err)

    # 6. Mark session ready.
    session_service.update_status(session_id, "ready")
    logger.info("DONE — session %s is now ready", session_id)


def main() -> None:
    init_database()
    args = sys.argv[1:]
    if not args:
        print("usage: python -m app.complete_generation <session_id>")
        sys.exit(1)
    complete(args[0])


if __name__ == "__main__":
    main()
