import { Link } from 'react-router-dom';
import Legal, { CONTACT_EMAIL } from './Legal.jsx';

export default function Refunds() {
  return (
    <Legal eyebrow="Policy" title="Refunds & cancellations">
      <p>
        StoryPlex sells <b>story credits</b>. One credit weaves one complete visual novel —
        its cast, artwork, script and voices. Credits are consumed the moment a story
        begins generating, because that is the point at which we incur the cost of
        producing it.
      </p>

      <h2>When we refund</h2>
      <ul>
        <li>
          <b>Failed generation.</b> If a story fails to generate because of a fault on our
          side, tell us and we will restore the credit. We keep a full ledger of every
          credit movement on your account, so this is easy for us to check.
        </li>
        <li>
          <b>Duplicate or incorrect charge.</b> If you were charged twice for the same
          purchase, or charged an amount that does not match the pack you selected, we
          refund the difference in full.
        </li>
        <li>
          <b>Unused credits, within 7 days.</b> If you bought credits within the last 7 days
          and have not spent any of them, write to us and we will refund that purchase in
          full.
        </li>
      </ul>

      <h2>When we don't refund</h2>
      <ul>
        <li>
          Credits already spent on a story that generated successfully. The story is
          delivered at that point, and it remains in your library.
        </li>
        <li>
          Dissatisfaction with the creative output. Stories are generated by AI from the
          premise you supply, and results vary. We would still rather hear about it —
          feedback is how the prompts improve.
        </li>
        <li>Purchases older than 7 days where credits have been used.</li>
      </ul>

      <h2>How to request one</h2>
      <p>
        Email <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a> from the address on
        your StoryPlex account, with the order reference from your{' '}
        <Link to="/billing">credits page</Link>. We aim to respond within 3 working days.
      </p>
      <p>
        Approved refunds are returned to the original payment method through our payment
        processor, Cashfree Payments. Your bank typically posts the money within 5–7
        working days of us initiating it.
      </p>

      <h2>Cancellations</h2>
      <p>
        There is no subscription and nothing recurring to cancel — credits are bought
        once and do not expire. A story that is part-way through generating cannot be
        cancelled, as the work is already underway.
      </p>
    </Legal>
  );
}
